# Generated by Django 2.1.7 on 2020-02-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200229_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='item',
            field=models.CharField(default='some-item', max_length=50),
        ),
    ]
