# Generated by Django 2.1.7 on 2020-02-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200229_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='item',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
