# Generated by Django 2.1.7 on 2020-02-29 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20190607_1117'),
        ('account', '0006_auto_20200229_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Job'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
