# Generated by Django 2.1.7 on 2020-02-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnelpermission',
            options={'ordering': ('app_name', 'name')},
        ),
        migrations.AddField(
            model_name='personnelpermission',
            name='app_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='personnelpermission',
            name='code_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
