# Generated by Django 2.1.2 on 2018-11-04 09:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shop.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', shop.utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', shop.utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashFlowType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', shop.utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', shop.utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='jobexpense',
            name='job',
        ),
        migrations.AlterField(
            model_name='job',
            name='feedback',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='JobExpense',
        ),
        migrations.AddField(
            model_name='cashflow',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.CashFlowType'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Job'),
        ),
    ]
