# Generated by Django 2.1.2 on 2018-11-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181104_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='banked',
            field=models.BooleanField(default=False),
        ),
    ]
