# Generated by Django 2.1.3 on 2018-11-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181105_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='job',
            name='total_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='job',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
