# Generated by Django 2.1.3 on 2018-11-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20181105_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='feedback',
        ),
        migrations.AddField(
            model_name='job',
            name='notes',
            field=models.CharField(default='notes', max_length=500),
            preserve_default=False,
        ),
    ]
