# Generated by Django 2.1.3 on 2018-11-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20181105_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('status', 'customer', '-created')},
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=1),
        ),
    ]
