# Generated by Django 2.1.3 on 2018-11-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20181106_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='long_description',
        ),
    ]
