# Generated by Django 2.1.2 on 2018-11-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20181104_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='completion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
