# Generated by Django 2.1.2 on 2018-11-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20181104_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
