# Generated by Django 2.1.3 on 2018-11-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20181105_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('0', 'Not started'), ('25', 'Starting'), ('50', 'Halfway done'), ('75', 'Almost done'), ('100', 'Done')], default='0', max_length=15),
        ),
    ]
