# Generated by Django 2.1.3 on 2018-11-07 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_job_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completed',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
