# Generated by Django 2.1.2 on 2018-11-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20181104_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashflow',
            options={'ordering': ('banked', 'category')},
        ),
        migrations.AddField(
            model_name='job',
            name='long_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='short_description',
            field=models.CharField(default='nothin', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashflowtype',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
