# Generated by Django 2.1.3 on 2018-11-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20181105_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('not started', 'Not started'), ('quarter', 'Starting'), ('halfway done', 'Halfway done'), ('almost done', 'Almost done'), ('completed', 'Done')], default='not started', max_length=15),
        ),
    ]
