# Generated by Django 2.1.3 on 2018-11-30 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20181124_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='profit',
            new_name='gross_profit',
        ),
    ]
