# Generated by Django 2.1.3 on 2018-12-01 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20181201_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashflow',
            options={'ordering': ('-created', 'job', 'category', 'banked')},
        ),
    ]
