# Generated by Django 2.1.3 on 2018-12-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20181201_0150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('status', '-start_date', 'customer')},
        ),
    ]
