# Generated by Django 2.1.7 on 2019-06-04 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20181205_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='description',
            new_name='description',
        ),
    ]
