# Generated by Django 2.1.7 on 2019-06-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20190604_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(1, 'Started'), (2, 'Finished'), (3, 'Delivered'), (4, 'Accepted')], default=1),
        ),
    ]
