# Generated by Django 2.1.7 on 2019-06-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20190605_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[('Started', 'Started'), ('Finished', 'Finished'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted')], default=1),
        ),
    ]
