# Generated by Django 2.1.7 on 2019-06-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20190605_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Started', 'Started'), ('Finished', 'Finished'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted')], default='Started', max_length=12),
        ),
    ]
