# Generated by Django 2.1.7 on 2019-06-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20190605_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default='Unknown address', max_length=50),
        ),
    ]
