# Generated by Django 2.2.10 on 2020-03-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20190607_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='gross_profit',
        ),
        migrations.RemoveField(
            model_name='job',
            name='total_expense',
        ),
        migrations.RemoveField(
            model_name='job',
            name='total_payment',
        ),
    ]
